import type {Metadata} from "next";
import "../globals.css";
import ReactQueryProvider
    from "@/app/(cache-sandbox)/client-cache-sandbox/provider/react-query.provider";

export const metadata: Metadata = {
    title: "Cache Sandbox",
    description: "Generated by create next app",
};

export default function CacheSandboxLayout({
                                               children,
                                           }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReactQueryProvider>
            {children}
        </ReactQueryProvider>
    );
}
